function _agent_help --description "agent help — top-level usage."
    echo "usage: agent <subcommand> [args...]"
    echo ""
    echo "  (no args)             — same as `agent ls`"
    echo ""
    echo "  ls                    — list agents (live sessions, meta-pane state, hidden state, worktree)"
    echo "  attach <name> [flags] — create-or-attach a per-agent session (un-hides if hidden)"
    echo "  rm [<name>] [flags]   — tear down worktree + session + branch (--all, --force)"
    echo "  hide [<name>]         — keep session/worktree alive but remove from the grid (--list)"
    echo "  restore [flags]       — rebuild the agents grid from live sessions (--include-hidden)"
    echo "  merged [-v]           — list agents whose branch is clean (safe to rm)"
    echo "  reload-plugin [name]  — rebuild + hot-reload a local zellij plugin (defaults to agents-bar)"
    echo ""
    echo "Per-subcommand help: `agent <sub> --help`."
end
